extends Node

signal experiment_completed(experiment_id: String, scientist_id: String, observations: Array, knowledge_gain: int)
signal observation_created(artifact_id: String, observation: Dictionary)
signal discovery_suspected(discovery_id: String)
signal discovery_confirmed(discovery_id: String)
signal discovery_named(discovery_id: String, player_name: String)
signal technology_unlocked(tech_id: String, tech_name: String)
signal rival_progressed(progress: int, message: String)
signal knowledge_updated(progress: int, state: String)
signal campaign_saved()
signal campaign_loaded()
signal budget_updated(funds: int, spent: int)
signal incident_occurred(incident: Dictionary)
signal incident_resolved(incident_id: String)
signal game_over(result: Dictionary)
signal market_updated(player_market: float, rivals: Array)
signal company_acquired(company_id: String, outcome: String)
signal offer_closed(company_id: String, fate: String)
signal rival_acquired(rival_id: String)
signal contract_updated()
signal event_updated(event_id: String, phase: String)
signal espionage_updated()
signal badge_earned(badge_id: String, badge_name: String)
signal rival_op(text: String)
